# Generated by Django 3.1.3 on 2023-01-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0002_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lastname',
        ),
    ]
