# Generated by Django 3.1.3 on 2023-01-14 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0004_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='diammhg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='fullname',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.member'),
        ),
        migrations.AddField(
            model_name='test',
            name='pluses',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='sysmmhg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
