# Generated by Django 3.1.3 on 2023-01-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0005_auto_20230114_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='bloodsugarmgdl',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='typesofbloodsugar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
