# Generated by Django 3.1.3 on 2023-01-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0006_auto_20230116_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='bodytemprature',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
