# Generated by Django 3.1.3 on 2023-01-16 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0007_test_bodytemprature'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='fromdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='todate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
