# Generated by Django 3.1.3 on 2023-01-18 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('healthapp', '0011_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='bloodsugarmgdl',
        ),
        migrations.RemoveField(
            model_name='test',
            name='bodytemprature',
        ),
        migrations.RemoveField(
            model_name='test',
            name='diammhg',
        ),
        migrations.RemoveField(
            model_name='test',
            name='pluses',
        ),
        migrations.RemoveField(
            model_name='test',
            name='sysmmhg',
        ),
        migrations.RemoveField(
            model_name='test',
            name='typesofbloodsugar',
        ),
        migrations.CreateModel(
            name='Temprature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodytemprature', models.CharField(blank=True, max_length=100, null=True)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('fullname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.member')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='Sugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typesofbloodsugar', models.CharField(blank=True, max_length=100, null=True)),
                ('bloodsugarmgdl', models.CharField(blank=True, max_length=100, null=True)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('fullname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.member')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.register')),
            ],
        ),
        migrations.CreateModel(
            name='Pressure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sysmmhg', models.CharField(blank=True, max_length=100, null=True)),
                ('diammhg', models.CharField(blank=True, max_length=100, null=True)),
                ('pluses', models.CharField(blank=True, max_length=100, null=True)),
                ('creationdate', models.DateTimeField(auto_now_add=True)),
                ('fullname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.member')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='healthapp.register')),
            ],
        ),
    ]
